package array;

public class TwoArrayTest03 {
	public static void main(String[] args) {
		int[] ar = {1, 2, 3};
		System.out.println(ar[0]);
		
		int[][] ar2 = {{1, 2, 3}, {1, 2, 3}, {1, 2, 3}};
		System.out.println(ar2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     );
		
	}
}
